# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'funnel_page.ui'
#
# Created: Wed Dec 11 10:29:39 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(297, 364)
        self.verticalLayout = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.xlimCheckBox = QtGui.QCheckBox(WizardPage)
        self.xlimCheckBox.setObjectName(_fromUtf8("xlimCheckBox"))
        self.horizontalLayout_2.addWidget(self.xlimCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(WizardPage)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.xlimLowSpinBox = QtGui.QDoubleSpinBox(WizardPage)
        self.xlimLowSpinBox.setMinimum(-10000.0)
        self.xlimLowSpinBox.setMaximum(10000.0)
        self.xlimLowSpinBox.setSingleStep(0.1)
        self.xlimLowSpinBox.setObjectName(_fromUtf8("xlimLowSpinBox"))
        self.horizontalLayout.addWidget(self.xlimLowSpinBox)
        self.label_11 = QtGui.QLabel(WizardPage)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.xlimHighSpinBox = QtGui.QDoubleSpinBox(WizardPage)
        self.xlimHighSpinBox.setMinimum(-10000.0)
        self.xlimHighSpinBox.setMaximum(10000.0)
        self.xlimHighSpinBox.setSingleStep(0.1)
        self.xlimHighSpinBox.setObjectName(_fromUtf8("xlimHighSpinBox"))
        self.horizontalLayout.addWidget(self.xlimHighSpinBox)
        self.label_9 = QtGui.QLabel(WizardPage)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ylimCheckBox = QtGui.QCheckBox(WizardPage)
        self.ylimCheckBox.setObjectName(_fromUtf8("ylimCheckBox"))
        self.horizontalLayout_3.addWidget(self.ylimCheckBox)
        self.ylim_layout = QtGui.QHBoxLayout()
        self.ylim_layout.setObjectName(_fromUtf8("ylim_layout"))
        self.label_8 = QtGui.QLabel(WizardPage)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ylim_layout.addWidget(self.label_8)
        self.ylimLowSpinBox = QtGui.QDoubleSpinBox(WizardPage)
        self.ylimLowSpinBox.setMinimum(-10000.0)
        self.ylimLowSpinBox.setMaximum(10000.0)
        self.ylimLowSpinBox.setSingleStep(0.1)
        self.ylimLowSpinBox.setObjectName(_fromUtf8("ylimLowSpinBox"))
        self.ylim_layout.addWidget(self.ylimLowSpinBox)
        self.label_12 = QtGui.QLabel(WizardPage)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ylim_layout.addWidget(self.label_12)
        self.ylimHighSpinBox = QtGui.QDoubleSpinBox(WizardPage)
        self.ylimHighSpinBox.setMinimum(-10000.0)
        self.ylimHighSpinBox.setMaximum(10000.0)
        self.ylimHighSpinBox.setSingleStep(0.1)
        self.ylimHighSpinBox.setObjectName(_fromUtf8("ylimHighSpinBox"))
        self.ylim_layout.addWidget(self.ylimHighSpinBox)
        self.label_10 = QtGui.QLabel(WizardPage)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ylim_layout.addWidget(self.label_10)
        self.horizontalLayout_3.addLayout(self.ylim_layout)
        spacerItem1 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.xlabCheckBox = QtGui.QCheckBox(WizardPage)
        self.xlabCheckBox.setObjectName(_fromUtf8("xlabCheckBox"))
        self.horizontalLayout_4.addWidget(self.xlabCheckBox)
        self.xlab_layout = QtGui.QHBoxLayout()
        self.xlab_layout.setObjectName(_fromUtf8("xlab_layout"))
        self.label = QtGui.QLabel(WizardPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.xlab_layout.addWidget(self.label)
        self.xlab_le = QtGui.QLineEdit(WizardPage)
        self.xlab_le.setText(_fromUtf8(""))
        self.xlab_le.setObjectName(_fromUtf8("xlab_le"))
        self.xlab_layout.addWidget(self.xlab_le)
        self.horizontalLayout_4.addLayout(self.xlab_layout)
        spacerItem2 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ylabCheckBox = QtGui.QCheckBox(WizardPage)
        self.ylabCheckBox.setObjectName(_fromUtf8("ylabCheckBox"))
        self.horizontalLayout_5.addWidget(self.ylabCheckBox)
        self.ylab_layout = QtGui.QHBoxLayout()
        self.ylab_layout.setObjectName(_fromUtf8("ylab_layout"))
        self.label_2 = QtGui.QLabel(WizardPage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ylab_layout.addWidget(self.label_2)
        self.ylab_le = QtGui.QLineEdit(WizardPage)
        self.ylab_le.setText(_fromUtf8(""))
        self.ylab_le.setObjectName(_fromUtf8("ylab_le"))
        self.ylab_layout.addWidget(self.ylab_le)
        self.horizontalLayout_5.addLayout(self.ylab_layout)
        spacerItem3 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(WizardPage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.stepsSpinBox = QtGui.QSpinBox(WizardPage)
        self.stepsSpinBox.setMinimum(2)
        self.stepsSpinBox.setMaximum(20)
        self.stepsSpinBox.setProperty("value", 5)
        self.stepsSpinBox.setObjectName(_fromUtf8("stepsSpinBox"))
        self.horizontalLayout_6.addWidget(self.stepsSpinBox)
        spacerItem4 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(WizardPage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.digitsSpinBox = QtGui.QSpinBox(WizardPage)
        self.digitsSpinBox.setMinimum(1)
        self.digitsSpinBox.setMaximum(10)
        self.digitsSpinBox.setProperty("value", 3)
        self.digitsSpinBox.setObjectName(_fromUtf8("digitsSpinBox"))
        self.horizontalLayout_7.addWidget(self.digitsSpinBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(WizardPage)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.addtau2ComboBox = QtGui.QComboBox(WizardPage)
        self.addtau2ComboBox.setObjectName(_fromUtf8("addtau2ComboBox"))
        self.addtau2ComboBox.addItem(_fromUtf8(""))
        self.addtau2ComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.addtau2ComboBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.reflineCheckBox = QtGui.QCheckBox(WizardPage)
        self.reflineCheckBox.setObjectName(_fromUtf8("reflineCheckBox"))
        self.horizontalLayout_9.addWidget(self.reflineCheckBox)
        self.label_6 = QtGui.QLabel(WizardPage)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.reflineSpinBox = QtGui.QDoubleSpinBox(WizardPage)
        self.reflineSpinBox.setMinimum(-10000.0)
        self.reflineSpinBox.setMaximum(10000.0)
        self.reflineSpinBox.setSingleStep(0.1)
        self.reflineSpinBox.setObjectName(_fromUtf8("reflineSpinBox"))
        self.horizontalLayout_9.addWidget(self.reflineSpinBox)
        spacerItem7 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label25 = QtGui.QLabel(WizardPage)
        self.label25.setObjectName(_fromUtf8("label25"))
        self.horizontalLayout_10.addWidget(self.label25)
        self.status_lbl = QtGui.QLabel(WizardPage)
        self.status_lbl.setObjectName(_fromUtf8("status_lbl"))
        self.horizontalLayout_10.addWidget(self.status_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.label.setBuddy(self.xlab_le)
        self.label_2.setBuddy(self.ylab_le)
        self.label_3.setBuddy(self.stepsSpinBox)
        self.label_4.setBuddy(self.digitsSpinBox)
        self.label_5.setBuddy(self.addtau2ComboBox)
        self.label_6.setBuddy(self.reflineSpinBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)
        WizardPage.setTabOrder(self.xlimCheckBox, self.xlimLowSpinBox)
        WizardPage.setTabOrder(self.xlimLowSpinBox, self.xlimHighSpinBox)
        WizardPage.setTabOrder(self.xlimHighSpinBox, self.ylimCheckBox)
        WizardPage.setTabOrder(self.ylimCheckBox, self.ylimLowSpinBox)
        WizardPage.setTabOrder(self.ylimLowSpinBox, self.ylimHighSpinBox)
        WizardPage.setTabOrder(self.ylimHighSpinBox, self.xlabCheckBox)
        WizardPage.setTabOrder(self.xlabCheckBox, self.xlab_le)
        WizardPage.setTabOrder(self.xlab_le, self.ylabCheckBox)
        WizardPage.setTabOrder(self.ylabCheckBox, self.ylab_le)
        WizardPage.setTabOrder(self.ylab_le, self.stepsSpinBox)
        WizardPage.setTabOrder(self.stepsSpinBox, self.digitsSpinBox)
        WizardPage.setTabOrder(self.digitsSpinBox, self.addtau2ComboBox)
        WizardPage.setTabOrder(self.addtau2ComboBox, self.reflineCheckBox)
        WizardPage.setTabOrder(self.reflineCheckBox, self.reflineSpinBox)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage", None))
        WizardPage.setTitle(_translate("WizardPage", "Funnel Plot Settings", None))
        WizardPage.setSubTitle(_translate("WizardPage", "Funnel Plot Parameters", None))
        self.xlimCheckBox.setToolTip(_translate("WizardPage", "x axis limits. If not checked, the function tries to set the x\n"
"axis limits to some sensible values.", None))
        self.xlimCheckBox.setText(_translate("WizardPage", "set xlims?", None))
        self.label_7.setText(_translate("WizardPage", "[", None))
        self.label_11.setText(_translate("WizardPage", ",", None))
        self.label_9.setText(_translate("WizardPage", "]", None))
        self.ylimCheckBox.setToolTip(_translate("WizardPage", "y axis limits. If not checked, the function tries to set the y\n"
"axis limits to some sensible values.", None))
        self.ylimCheckBox.setText(_translate("WizardPage", "set ylims?", None))
        self.label_8.setText(_translate("WizardPage", "[", None))
        self.label_12.setText(_translate("WizardPage", ",", None))
        self.label_10.setText(_translate("WizardPage", "]", None))
        self.xlabCheckBox.setText(_translate("WizardPage", "set xlabel?", None))
        self.label.setText(_translate("WizardPage", "xlabel:", None))
        self.ylabCheckBox.setText(_translate("WizardPage", "set ylabel?", None))
        self.label_2.setText(_translate("WizardPage", "ylabel:", None))
        self.label_3.setText(_translate("WizardPage", "steps:", None))
        self.label_4.setText(_translate("WizardPage", "digits:", None))
        self.label_5.setText(_translate("WizardPage", "<html><head/><body><p>add τ<span style=\" vertical-align:super;\">2</span>:</p></body></html>", None))
        self.addtau2ComboBox.setItemText(0, _translate("WizardPage", "no", None))
        self.addtau2ComboBox.setItemText(1, _translate("WizardPage", "yes", None))
        self.reflineCheckBox.setText(_translate("WizardPage", "Set refline?", None))
        self.label_6.setText(_translate("WizardPage", "refline:", None))
        self.label25.setText(_translate("WizardPage", "status: ", None))
        self.status_lbl.setText(_translate("WizardPage", "actualstatus", None))

import icons_rc
