"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['launch.py']
DATA_FILES = ['/opt/local/Library/Frameworks/R.framework/Versions/3.0/Resources']
OPTIONS = {'argv_emulation': True, 'no_strip': True, 'resources': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
