# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sat Aug 30 21:08:52 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(918, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/general/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecent_Data = QtGui.QMenu(self.menuFile)
        self.menuRecent_Data.setObjectName(_fromUtf8("menuRecent_Data"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuMeta_Analysis = QtGui.QMenu(self.menuAnalysis)
        self.menuMeta_Analysis.setObjectName(_fromUtf8("menuMeta_Analysis"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuData_Exploration = QtGui.QMenu(self.menubar)
        self.menuData_Exploration.setObjectName(_fromUtf8("menuData_Exploration"))
        self.menuPublication_Bias_2 = QtGui.QMenu(self.menuData_Exploration)
        self.menuPublication_Bias_2.setObjectName(_fromUtf8("menuPublication_Bias_2"))
        self.menuThrough_the_looking_glass = QtGui.QMenu(self.menubar)
        self.menuThrough_the_looking_glass.setObjectName(_fromUtf8("menuThrough_the_looking_glass"))
        self.menuEffect_Size = QtGui.QMenu(self.menubar)
        self.menuEffect_Size.setObjectName(_fromUtf8("menuEffect_Size"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/add_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/folder_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/floppy_disk_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionClear_Selected_Cells = QtGui.QAction(MainWindow)
        self.actionClear_Selected_Cells.setObjectName(_fromUtf8("actionClear_Selected_Cells"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionChange_Column_Format = QtGui.QAction(MainWindow)
        self.actionChange_Column_Format.setObjectName(_fromUtf8("actionChange_Column_Format"))
        self.actionRename_Column = QtGui.QAction(MainWindow)
        self.actionRename_Column.setObjectName(_fromUtf8("actionRename_Column"))
        self.actionMark_Column_as_Label = QtGui.QAction(MainWindow)
        self.actionMark_Column_as_Label.setObjectName(_fromUtf8("actionMark_Column_as_Label"))
        self.actionUnmark_Column_as_Label = QtGui.QAction(MainWindow)
        self.actionUnmark_Column_as_Label.setObjectName(_fromUtf8("actionUnmark_Column_as_Label"))
        self.actionDecimal_Places = QtGui.QAction(MainWindow)
        self.actionDecimal_Places.setObjectName(_fromUtf8("actionDecimal_Places"))
        self.actionTable_Preferences = QtGui.QAction(MainWindow)
        self.actionTable_Preferences.setObjectName(_fromUtf8("actionTable_Preferences"))
        self.actionShow_toolbar = QtGui.QAction(MainWindow)
        self.actionShow_toolbar.setObjectName(_fromUtf8("actionShow_toolbar"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCalculate_Effect_Size = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/calculate_effect_size.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculate_Effect_Size.setIcon(icon4)
        self.actionCalculate_Effect_Size.setObjectName(_fromUtf8("actionCalculate_Effect_Size"))
        self.actionStandard_Meta_Analysis = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/meta_analysis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandard_Meta_Analysis.setIcon(icon5)
        self.actionStandard_Meta_Analysis.setObjectName(_fromUtf8("actionStandard_Meta_Analysis"))
        self.actionCumulative = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/cum_meta_analysis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCumulative.setIcon(icon6)
        self.actionCumulative.setObjectName(_fromUtf8("actionCumulative"))
        self.actionLeave_one_out = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/leave_one_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeave_one_out.setIcon(icon7)
        self.actionLeave_one_out.setObjectName(_fromUtf8("actionLeave_one_out"))
        self.actionSubgroup = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/subgroup_ma.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSubgroup.setIcon(icon8)
        self.actionSubgroup.setObjectName(_fromUtf8("actionSubgroup"))
        self.actionMeta_Regression = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/meta_reg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMeta_Regression.setIcon(icon9)
        self.actionMeta_Regression.setObjectName(_fromUtf8("actionMeta_Regression"))
        self.actionImportCSV = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/box_download_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportCSV.setIcon(icon10)
        self.actionImportCSV.setObjectName(_fromUtf8("actionImportCSV"))
        self.actionExportCSV = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/box_upload_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportCSV.setIcon(icon11)
        self.actionExportCSV.setObjectName(_fromUtf8("actionExportCSV"))
        self.actionTransform_Effect_Size = QtGui.QAction(MainWindow)
        self.actionTransform_Effect_Size.setObjectName(_fromUtf8("actionTransform_Effect_Size"))
        self.actionBootstrapped_Meta_Analysis = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/analysis_icons/images/boot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBootstrapped_Meta_Analysis.setIcon(icon12)
        self.actionBootstrapped_Meta_Analysis.setObjectName(_fromUtf8("actionBootstrapped_Meta_Analysis"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setMenuRole(QtGui.QAction.AboutRole)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.actionFail_Safe_N = QtGui.QAction(MainWindow)
        self.actionFail_Safe_N.setObjectName(_fromUtf8("actionFail_Safe_N"))
        self.actionFunnel_Plot = QtGui.QAction(MainWindow)
        self.actionFunnel_Plot.setObjectName(_fromUtf8("actionFunnel_Plot"))
        self.actionResetAnalysisChoices = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/images/function_icon_set/refresh_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResetAnalysisChoices.setIcon(icon13)
        self.actionResetAnalysisChoices.setObjectName(_fromUtf8("actionResetAnalysisChoices"))
        self.actionScatterplot = QtGui.QAction(MainWindow)
        self.actionScatterplot.setObjectName(_fromUtf8("actionScatterplot"))
        self.actionHistogram = QtGui.QAction(MainWindow)
        self.actionHistogram.setObjectName(_fromUtf8("actionHistogram"))
        self.actionPhyloMA = QtGui.QAction(MainWindow)
        self.actionPhyloMA.setObjectName(_fromUtf8("actionPhyloMA"))
        self.actionModel_Building = QtGui.QAction(MainWindow)
        self.actionModel_Building.setObjectName(_fromUtf8("actionModel_Building"))
        self.actionR_log = QtGui.QAction(MainWindow)
        self.actionR_log.setObjectName(_fromUtf8("actionR_log"))
        self.actionContingency_Table = QtGui.QAction(MainWindow)
        self.actionContingency_Table.setObjectName(_fromUtf8("actionContingency_Table"))
        self.actionImpute_Missing_Data = QtGui.QAction(MainWindow)
        self.actionImpute_Missing_Data.setObjectName(_fromUtf8("actionImpute_Missing_Data"))
        self.actionMultiple_Imputation_Meta_Analysis = QtGui.QAction(MainWindow)
        self.actionMultiple_Imputation_Meta_Analysis.setObjectName(_fromUtf8("actionMultiple_Imputation_Meta_Analysis"))
        self.actionGet_help_online = QtGui.QAction(MainWindow)
        self.actionGet_help_online.setObjectName(_fromUtf8("actionGet_help_online"))
        self.actionPermuted_MA = QtGui.QAction(MainWindow)
        self.actionPermuted_MA.setObjectName(_fromUtf8("actionPermuted_MA"))
        self.actionPermuted_metareg = QtGui.QAction(MainWindow)
        self.actionPermuted_metareg.setObjectName(_fromUtf8("actionPermuted_metareg"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionImportCSV)
        self.menuFile.addAction(self.actionExportCSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecent_Data.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionClear_Selected_Cells)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionShow_toolbar)
        self.menuEdit.addAction(self.actionTable_Preferences)
        self.menuMeta_Analysis.addAction(self.actionStandard_Meta_Analysis)
        self.menuMeta_Analysis.addAction(self.actionCumulative)
        self.menuMeta_Analysis.addAction(self.actionLeave_one_out)
        self.menuMeta_Analysis.addAction(self.actionSubgroup)
        self.menuMeta_Analysis.addAction(self.actionBootstrapped_Meta_Analysis)
        self.menuAnalysis.addAction(self.menuMeta_Analysis.menuAction())
        self.menuAnalysis.addAction(self.actionMeta_Regression)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionPhyloMA)
        self.menuAnalysis.addAction(self.actionModel_Building)
        self.menuAnalysis.addAction(self.actionMultiple_Imputation_Meta_Analysis)
        self.menuAnalysis.addAction(self.actionPermuted_MA)
        self.menuAnalysis.addAction(self.actionPermuted_metareg)
        self.menuAbout.addAction(self.action_about)
        self.menuAbout.addAction(self.actionGet_help_online)
        self.menuPublication_Bias_2.addAction(self.actionFail_Safe_N)
        self.menuPublication_Bias_2.addAction(self.actionFunnel_Plot)
        self.menuData_Exploration.addAction(self.actionScatterplot)
        self.menuData_Exploration.addAction(self.actionHistogram)
        self.menuData_Exploration.addAction(self.menuPublication_Bias_2.menuAction())
        self.menuData_Exploration.addAction(self.actionContingency_Table)
        self.menuData_Exploration.addSeparator()
        self.menuData_Exploration.addAction(self.actionImpute_Missing_Data)
        self.menuThrough_the_looking_glass.addAction(self.actionR_log)
        self.menuEffect_Size.addAction(self.actionCalculate_Effect_Size)
        self.menuEffect_Size.addAction(self.actionTransform_Effect_Size)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuEffect_Size.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuData_Exploration.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuThrough_the_looking_glass.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionImportCSV)
        self.toolBar.addAction(self.actionExportCSV)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCalculate_Effect_Size)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStandard_Meta_Analysis)
        self.toolBar.addAction(self.actionCumulative)
        self.toolBar.addAction(self.actionLeave_one_out)
        self.toolBar.addAction(self.actionSubgroup)
        self.toolBar.addAction(self.actionMeta_Regression)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionResetAnalysisChoices)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRecent_Data.setTitle(_translate("MainWindow", "Recent Data...", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuMeta_Analysis.setTitle(_translate("MainWindow", "Meta-Analysis", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuData_Exploration.setTitle(_translate("MainWindow", "Data Exploration", None))
        self.menuPublication_Bias_2.setTitle(_translate("MainWindow", "Publication Bias", None))
        self.menuThrough_the_looking_glass.setTitle(_translate("MainWindow", "Through the looking glass", None))
        self.menuEffect_Size.setTitle(_translate("MainWindow", "Effect Size", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setToolTip(_translate("MainWindow", "New Dataset", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open file", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionClear_Selected_Cells.setText(_translate("MainWindow", "Clear Selected Cells", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionChange_Column_Format.setText(_translate("MainWindow", "Change Column Format", None))
        self.actionRename_Column.setText(_translate("MainWindow", "Rename Column", None))
        self.actionMark_Column_as_Label.setText(_translate("MainWindow", "Mark Column as Label", None))
        self.actionUnmark_Column_as_Label.setText(_translate("MainWindow", "Unmark Column as Label", None))
        self.actionDecimal_Places.setText(_translate("MainWindow", "Decimal Places", None))
        self.actionTable_Preferences.setText(_translate("MainWindow", "Preferences ...", None))
        self.actionShow_toolbar.setText(_translate("MainWindow", "Show toolbar", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionCalculate_Effect_Size.setText(_translate("MainWindow", "Calculate Effect Size", None))
        self.actionStandard_Meta_Analysis.setText(_translate("MainWindow", "Standard Meta-Analysis", None))
        self.actionCumulative.setText(_translate("MainWindow", "Cumulative analysis", None))
        self.actionLeave_one_out.setText(_translate("MainWindow", "Leave-one-out analysis", None))
        self.actionSubgroup.setText(_translate("MainWindow", "Subgroup analysis", None))
        self.actionMeta_Regression.setText(_translate("MainWindow", "Meta-Regression", None))
        self.actionImportCSV.setText(_translate("MainWindow", "Import CSV", None))
        self.actionExportCSV.setText(_translate("MainWindow", "Export CSV", None))
        self.actionTransform_Effect_Size.setText(_translate("MainWindow", "Transform Effect Size", None))
        self.actionBootstrapped_Meta_Analysis.setText(_translate("MainWindow", "Bootstrapped Meta-Analysis", None))
        self.action_about.setText(_translate("MainWindow", "About", None))
        self.actionFail_Safe_N.setText(_translate("MainWindow", "Fail-Safe N", None))
        self.actionFunnel_Plot.setText(_translate("MainWindow", "Funnel Plot", None))
        self.actionResetAnalysisChoices.setText(_translate("MainWindow", "Reset Analysis Choices", None))
        self.actionResetAnalysisChoices.setToolTip(_translate("MainWindow", "Reset choices made in analysis screens to the defaults", None))
        self.actionScatterplot.setText(_translate("MainWindow", "Scatterplot", None))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram", None))
        self.actionPhyloMA.setText(_translate("MainWindow", "Phylogenetic Meta-Analysis", None))
        self.actionModel_Building.setText(_translate("MainWindow", "Model Building", None))
        self.actionR_log.setText(_translate("MainWindow", "R output viewer", None))
        self.actionContingency_Table.setText(_translate("MainWindow", "Contingency Table", None))
        self.actionImpute_Missing_Data.setText(_translate("MainWindow", "Impute Missing Data", None))
        self.actionMultiple_Imputation_Meta_Analysis.setText(_translate("MainWindow", "Multiple Imputation Meta-Analysis", None))
        self.actionGet_help_online.setText(_translate("MainWindow", "Get help online", None))
        self.actionPermuted_MA.setText(_translate("MainWindow", "Randomized (Permuted) Meta-Analysis", None))
        self.actionPermuted_metareg.setText(_translate("MainWindow", "Randomized (Permuted) Meta-Regression", None))

import icons_rc
