# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_covariates_page.ui'
#
# Created: Thu Jan 16 16:30:56 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(629, 426)
        self.verticalLayout_8 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame = QtGui.QFrame(WizardPage)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.available_covs_listWidget = QtGui.QListWidget(self.groupBox)
        self.available_covs_listWidget.setObjectName(_fromUtf8("available_covs_listWidget"))
        self.verticalLayout_7.addWidget(self.available_covs_listWidget)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.add_all_pushbutton = QtGui.QPushButton(self.frame_2)
        self.add_all_pushbutton.setObjectName(_fromUtf8("add_all_pushbutton"))
        self.verticalLayout_5.addWidget(self.add_all_pushbutton)
        self.add_pushbutton = QtGui.QPushButton(self.frame_2)
        self.add_pushbutton.setObjectName(_fromUtf8("add_pushbutton"))
        self.verticalLayout_5.addWidget(self.add_pushbutton)
        self.remove_pushButton = QtGui.QPushButton(self.frame_2)
        self.remove_pushButton.setObjectName(_fromUtf8("remove_pushButton"))
        self.verticalLayout_5.addWidget(self.remove_pushButton)
        self.remove_all_pushButton = QtGui.QPushButton(self.frame_2)
        self.remove_all_pushButton.setObjectName(_fromUtf8("remove_all_pushButton"))
        self.verticalLayout_5.addWidget(self.remove_all_pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.selected_covs_listWidget = QtGui.QListWidget(self.groupBox_3)
        self.selected_covs_listWidget.setObjectName(_fromUtf8("selected_covs_listWidget"))
        self.verticalLayout_4.addWidget(self.selected_covs_listWidget)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.unavailable_covs_listWidget = QtGui.QListWidget(self.groupBox_4)
        self.unavailable_covs_listWidget.setEnabled(True)
        self.unavailable_covs_listWidget.setObjectName(_fromUtf8("unavailable_covs_listWidget"))
        item = QtGui.QListWidgetItem()
        self.unavailable_covs_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.unavailable_covs_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.unavailable_covs_listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.unavailable_covs_listWidget)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addWidget(self.frame)
        self.line = QtGui.QFrame(WizardPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_8.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.model_type_groupBox = QtGui.QGroupBox(WizardPage)
        self.model_type_groupBox.setObjectName(_fromUtf8("model_type_groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.model_type_groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.random_effects_radio_btn = QtGui.QRadioButton(self.model_type_groupBox)
        self.random_effects_radio_btn.setChecked(True)
        self.random_effects_radio_btn.setObjectName(_fromUtf8("random_effects_radio_btn"))
        self.verticalLayout_2.addWidget(self.random_effects_radio_btn)
        self.fixed_effects_radio_btn = QtGui.QRadioButton(self.model_type_groupBox)
        self.fixed_effects_radio_btn.setObjectName(_fromUtf8("fixed_effects_radio_btn"))
        self.verticalLayout_2.addWidget(self.fixed_effects_radio_btn)
        self.horizontalLayout.addWidget(self.model_type_groupBox)
        self.random_effects_method_GroupBox = QtGui.QGroupBox(WizardPage)
        self.random_effects_method_GroupBox.setObjectName(_fromUtf8("random_effects_method_GroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.random_effects_method_GroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.random_effects_method_ComboBox = QtGui.QComboBox(self.random_effects_method_GroupBox)
        self.random_effects_method_ComboBox.setObjectName(_fromUtf8("random_effects_method_ComboBox"))
        self.random_effects_method_ComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.random_effects_method_ComboBox)
        self.horizontalLayout.addWidget(self.random_effects_method_GroupBox)
        self.groupBox_2 = QtGui.QGroupBox(WizardPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.conf_level_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.conf_level_spinbox.setDecimals(1)
        self.conf_level_spinbox.setMinimum(70.0)
        self.conf_level_spinbox.setMaximum(99.9)
        self.conf_level_spinbox.setSingleStep(0.1)
        self.conf_level_spinbox.setProperty("value", 95.0)
        self.conf_level_spinbox.setObjectName(_fromUtf8("conf_level_spinbox"))
        self.verticalLayout.addWidget(self.conf_level_spinbox)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage", None))
        self.groupBox.setTitle(_translate("WizardPage", "Available Covariates", None))
        self.add_all_pushbutton.setText(_translate("WizardPage", ">>", None))
        self.add_pushbutton.setText(_translate("WizardPage", ">", None))
        self.remove_pushButton.setText(_translate("WizardPage", "<", None))
        self.remove_all_pushButton.setText(_translate("WizardPage", "<<", None))
        self.groupBox_3.setTitle(_translate("WizardPage", "Selected Covariates", None))
        self.groupBox_4.setTitle(_translate("WizardPage", "Unavailable Covariates", None))
        __sortingEnabled = self.unavailable_covs_listWidget.isSortingEnabled()
        self.unavailable_covs_listWidget.setSortingEnabled(False)
        item = self.unavailable_covs_listWidget.item(0)
        item.setText(_translate("WizardPage", "cov1", None))
        item = self.unavailable_covs_listWidget.item(1)
        item.setText(_translate("WizardPage", "cov2", None))
        item = self.unavailable_covs_listWidget.item(2)
        item.setText(_translate("WizardPage", "cov3", None))
        self.unavailable_covs_listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("WizardPage", "(selected studies have missing data for these covariates)", None))
        self.model_type_groupBox.setTitle(_translate("WizardPage", "Model Type", None))
        self.random_effects_radio_btn.setText(_translate("WizardPage", "random effects", None))
        self.fixed_effects_radio_btn.setText(_translate("WizardPage", "fixed effects", None))
        self.random_effects_method_GroupBox.setTitle(_translate("WizardPage", "Random Effects Method", None))
        self.random_effects_method_ComboBox.setItemText(0, _translate("WizardPage", "clear and then populate me", None))
        self.groupBox_2.setTitle(_translate("WizardPage", "Confidence Level", None))
        self.conf_level_spinbox.setSuffix(_translate("WizardPage", " %", None))

