# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phylo_model_design_page.ui'
#
# Created: Wed Feb 26 16:35:41 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(585, 577)
        self.verticalLayout_7 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(WizardPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.label_2 = QtGui.QLabel(WizardPage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.line = QtGui.QFrame(WizardPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.groupBox = QtGui.QGroupBox(WizardPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.random_drift_frame = QtGui.QFrame(self.groupBox)
        self.random_drift_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.random_drift_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.random_drift_frame.setObjectName(_fromUtf8("random_drift_frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.random_drift_frame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.BM_radioButton = QtGui.QRadioButton(self.random_drift_frame)
        self.BM_radioButton.setChecked(True)
        self.BM_radioButton.setObjectName(_fromUtf8("BM_radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(WizardPage)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.BM_radioButton)
        self.horizontalLayout_2.addWidget(self.BM_radioButton)
        self.label_4 = QtGui.QLabel(self.random_drift_frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.random_drift_frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lambda_doubleSpinBox = QtGui.QDoubleSpinBox(self.random_drift_frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lambda_doubleSpinBox.setFont(font)
        self.lambda_doubleSpinBox.setDecimals(1)
        self.lambda_doubleSpinBox.setMaximum(1.0)
        self.lambda_doubleSpinBox.setSingleStep(0.1)
        self.lambda_doubleSpinBox.setProperty("value", 1.0)
        self.lambda_doubleSpinBox.setObjectName(_fromUtf8("lambda_doubleSpinBox"))
        self.horizontalLayout.addWidget(self.lambda_doubleSpinBox)
        self.label_7 = QtGui.QLabel(self.random_drift_frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 5, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_8 = QtGui.QLabel(self.random_drift_frame)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.random_drift_frame)
        self.stabilizing_selection_frame = QtGui.QFrame(self.groupBox)
        self.stabilizing_selection_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stabilizing_selection_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.stabilizing_selection_frame.setObjectName(_fromUtf8("stabilizing_selection_frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.stabilizing_selection_frame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.OU_radioButton = QtGui.QRadioButton(self.stabilizing_selection_frame)
        self.OU_radioButton.setChecked(False)
        self.OU_radioButton.setObjectName(_fromUtf8("OU_radioButton"))
        self.buttonGroup.addButton(self.OU_radioButton)
        self.horizontalLayout_4.addWidget(self.OU_radioButton)
        self.label_5 = QtGui.QLabel(self.stabilizing_selection_frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.stabilizing_selection_frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.alpha_doubleSpinBox = QtGui.QDoubleSpinBox(self.stabilizing_selection_frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.alpha_doubleSpinBox.setFont(font)
        self.alpha_doubleSpinBox.setDecimals(1)
        self.alpha_doubleSpinBox.setMaximum(1000000000.0)
        self.alpha_doubleSpinBox.setSingleStep(0.1)
        self.alpha_doubleSpinBox.setProperty("value", 1.0)
        self.alpha_doubleSpinBox.setObjectName(_fromUtf8("alpha_doubleSpinBox"))
        self.horizontalLayout_3.addWidget(self.alpha_doubleSpinBox)
        self.label_11 = QtGui.QLabel(self.stabilizing_selection_frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_9 = QtGui.QLabel(self.stabilizing_selection_frame)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addWidget(self.stabilizing_selection_frame)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(WizardPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.polytomies_info_label = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.polytomies_info_label.setFont(font)
        self.polytomies_info_label.setObjectName(_fromUtf8("polytomies_info_label"))
        self.verticalLayout.addWidget(self.polytomies_info_label)
        self.randpoly_checkBox = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.randpoly_checkBox.setFont(font)
        self.randpoly_checkBox.setObjectName(_fromUtf8("randpoly_checkBox"))
        self.verticalLayout.addWidget(self.randpoly_checkBox)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        spacerItem6 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage", None))
        self.label.setText(_translate("WizardPage", "This tool helps design your phylogenetic meta-analysis model.", None))
        self.label_2.setText(_translate("WizardPage", "Please select your model of evolution and assumptions.", None))
        self.groupBox.setTitle(_translate("WizardPage", "Model Type for phylogenetic correlations", None))
        self.BM_radioButton.setText(_translate("WizardPage", "random drift", None))
        self.label_4.setText(_translate("WizardPage", "  (Brownian-motion model, or BM)", None))
        self.label_6.setText(_translate("WizardPage", "Pagel\'s λ =", None))
        self.label_7.setText(_translate("WizardPage", "(default = 1.0)", None))
        self.label_8.setText(_translate("WizardPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">The value of λ can range from 1 to 0, where 1 assumes a full BM model (default). A value of zero assumes no phylogenetic correlations, and values between 1 and zero manipulate the overall contribution of the phylogeny in defining the phylogenetic correlations. </span><span style=\" font-weight:400; font-style:italic;\">This model assumes that phylogenetic correlations erode </span><span style=\" font-style:italic;\">linearly</span><span style=\" font-weight:400; font-style:italic;\"> with time of convergence.</span></p></body></html>", None))
        self.OU_radioButton.setText(_translate("WizardPage", "stabilizing selection", None))
        self.label_5.setText(_translate("WizardPage", "  (Ornstein-Uhlenbeck model, or OU)", None))
        self.label_10.setText(_translate("WizardPage", "Martins and Hansen\'s α =", None))
        self.label_11.setText(_translate("WizardPage", "(default = 1.0)", None))
        self.label_9.setText(_translate("WizardPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">The value of α can range from zero to infinity, where values near zero yield a model similiar to BM with λ = 1. The value of α can be interpreted as the strength of selection, with selection here acting to erase phylogenetic correlations across the entire tree. </span><span style=\" font-weight:400; font-style:italic;\">This model assumes that phylogenetic correlations erode </span><span style=\" font-style:italic;\">exponentially</span><span style=\" font-weight:400; font-style:italic;\"> with time of divergence.</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("WizardPage", "Dealing with polytomies in your tree", None))
        self.polytomies_info_label.setText(_translate("WizardPage", "Your current tree, (insert filename), has (insert count) polytomies.", None))
        self.randpoly_checkBox.setText(_translate("WizardPage", "Randomly resolve these polytomies?", None))

