# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phylo_analysis_details_page.ui'
#
# Created: Thu Mar  6 09:37:21 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(490, 447)
        self.verticalLayout_4 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(WizardPage)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.details_tab = QtGui.QWidget()
        self.details_tab.setObjectName(_fromUtf8("details_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.details_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.details_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.effect_comboBox = QtGui.QComboBox(self.groupBox)
        self.effect_comboBox.setObjectName(_fromUtf8("effect_comboBox"))
        self.gridLayout.addWidget(self.effect_comboBox, 0, 1, 1, 1)
        self.variance_comboBox = QtGui.QComboBox(self.groupBox)
        self.variance_comboBox.setObjectName(_fromUtf8("variance_comboBox"))
        self.gridLayout.addWidget(self.variance_comboBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.species_comboBox = QtGui.QComboBox(self.groupBox)
        self.species_comboBox.setObjectName(_fromUtf8("species_comboBox"))
        self.horizontalLayout_2.addWidget(self.species_comboBox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.line = QtGui.QFrame(self.details_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.groupBox_2 = QtGui.QGroupBox(self.details_tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.random_effects_method_GroupBox = QtGui.QGroupBox(self.groupBox_2)
        self.random_effects_method_GroupBox.setObjectName(_fromUtf8("random_effects_method_GroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.random_effects_method_GroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.random_effects_method_ComboBox = QtGui.QComboBox(self.random_effects_method_GroupBox)
        self.random_effects_method_ComboBox.setObjectName(_fromUtf8("random_effects_method_ComboBox"))
        self.random_effects_method_ComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.random_effects_method_ComboBox)
        self.horizontalLayout_5.addWidget(self.random_effects_method_GroupBox)
        self.conf_level_groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.conf_level_groupBox.setObjectName(_fromUtf8("conf_level_groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.conf_level_groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.conf_level_spinbox = QtGui.QDoubleSpinBox(self.conf_level_groupBox)
        self.conf_level_spinbox.setDecimals(1)
        self.conf_level_spinbox.setMinimum(70.0)
        self.conf_level_spinbox.setMaximum(99.9)
        self.conf_level_spinbox.setSingleStep(0.1)
        self.conf_level_spinbox.setProperty("value", 95.0)
        self.conf_level_spinbox.setObjectName(_fromUtf8("conf_level_spinbox"))
        self.horizontalLayout.addWidget(self.conf_level_spinbox)
        self.horizontalLayout_5.addWidget(self.conf_level_groupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.include_species_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.include_species_checkBox.setChecked(True)
        self.include_species_checkBox.setObjectName(_fromUtf8("include_species_checkBox"))
        self.verticalLayout.addWidget(self.include_species_checkBox)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.details_tab, _fromUtf8(""))
        self.forest_plot_tab = QtGui.QWidget()
        self.forest_plot_tab.setObjectName(_fromUtf8("forest_plot_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.forest_plot_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.forest_plot_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.col1_str_edit = QtGui.QLineEdit(self.groupBox_3)
        self.col1_str_edit.setObjectName(_fromUtf8("col1_str_edit"))
        self.gridLayout_2.addWidget(self.col1_str_edit, 0, 1, 1, 1)
        self.show_1 = QtGui.QCheckBox(self.groupBox_3)
        self.show_1.setChecked(True)
        self.show_1.setObjectName(_fromUtf8("show_1"))
        self.gridLayout_2.addWidget(self.show_1, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.col2_str_edit = QtGui.QLineEdit(self.groupBox_3)
        self.col2_str_edit.setObjectName(_fromUtf8("col2_str_edit"))
        self.gridLayout_2.addWidget(self.col2_str_edit, 1, 1, 1, 1)
        self.show_2 = QtGui.QCheckBox(self.groupBox_3)
        self.show_2.setChecked(True)
        self.show_2.setObjectName(_fromUtf8("show_2"))
        self.gridLayout_2.addWidget(self.show_2, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.col3_str_edit = QtGui.QLineEdit(self.groupBox_3)
        self.col3_str_edit.setObjectName(_fromUtf8("col3_str_edit"))
        self.gridLayout_2.addWidget(self.col3_str_edit, 2, 1, 1, 1)
        self.show_3 = QtGui.QCheckBox(self.groupBox_3)
        self.show_3.setChecked(True)
        self.show_3.setObjectName(_fromUtf8("show_3"))
        self.gridLayout_2.addWidget(self.show_3, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.col4_str_edit = QtGui.QLineEdit(self.groupBox_3)
        self.col4_str_edit.setObjectName(_fromUtf8("col4_str_edit"))
        self.gridLayout_2.addWidget(self.col4_str_edit, 3, 1, 1, 1)
        self.show_4 = QtGui.QCheckBox(self.groupBox_3)
        self.show_4.setChecked(True)
        self.show_4.setObjectName(_fromUtf8("show_4"))
        self.gridLayout_2.addWidget(self.show_4, 3, 2, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.x_lbl_le = QtGui.QLineEdit(self.forest_plot_tab)
        self.x_lbl_le.setObjectName(_fromUtf8("x_lbl_le"))
        self.gridLayout_3.addWidget(self.x_lbl_le, 0, 2, 1, 1)
        self.plot_lb_le = QtGui.QLineEdit(self.forest_plot_tab)
        self.plot_lb_le.setObjectName(_fromUtf8("plot_lb_le"))
        self.gridLayout_3.addWidget(self.plot_lb_le, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.forest_plot_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.forest_plot_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.plot_ub_le = QtGui.QLineEdit(self.forest_plot_tab)
        self.plot_ub_le.setObjectName(_fromUtf8("plot_ub_le"))
        self.gridLayout_3.addWidget(self.plot_ub_le, 2, 2, 1, 1)
        self.x_ticks_le = QtGui.QLineEdit(self.forest_plot_tab)
        self.x_ticks_le.setObjectName(_fromUtf8("x_ticks_le"))
        self.gridLayout_3.addWidget(self.x_ticks_le, 4, 2, 1, 1)
        self.show_summary_line = QtGui.QCheckBox(self.forest_plot_tab)
        self.show_summary_line.setText(_fromUtf8(""))
        self.show_summary_line.setChecked(True)
        self.show_summary_line.setObjectName(_fromUtf8("show_summary_line"))
        self.gridLayout_3.addWidget(self.show_summary_line, 5, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.forest_plot_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.forest_plot_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.forest_plot_tab)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.forest_plot_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.image_path = QtGui.QLineEdit(self.forest_plot_tab)
        self.image_path.setObjectName(_fromUtf8("image_path"))
        self.horizontalLayout_6.addWidget(self.image_path)
        self.save_btn = QtGui.QPushButton(self.forest_plot_tab)
        self.save_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.horizontalLayout_6.addWidget(self.save_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.forest_plot_tab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(WizardPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage", None))
        self.groupBox.setTitle(_translate("WizardPage", "Data Location", None))
        self.label_2.setText(_translate("WizardPage", "Variance", None))
        self.label.setText(_translate("WizardPage", "Effect Size", None))
        self.label_3.setText(_translate("WizardPage", "Species", None))
        self.groupBox_2.setTitle(_translate("WizardPage", "Analysis Details", None))
        self.random_effects_method_GroupBox.setTitle(_translate("WizardPage", "Random Effects Method", None))
        self.random_effects_method_ComboBox.setItemText(0, _translate("WizardPage", "clear and then populate me", None))
        self.conf_level_groupBox.setTitle(_translate("WizardPage", "Confidence Level", None))
        self.conf_level_spinbox.setSuffix(_translate("WizardPage", " %", None))
        self.include_species_checkBox.setText(_translate("WizardPage", "Include species as random factor?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.details_tab), _translate("WizardPage", "Analysis Details", None))
        self.groupBox_3.setTitle(_translate("WizardPage", "column labels", None))
        self.label_5.setToolTip(_translate("WizardPage", "Text for column title that appears on forest plot", None))
        self.label_5.setText(_translate("WizardPage", "col 1 label:", None))
        self.col1_str_edit.setText(_translate("WizardPage", "Studies", None))
        self.show_1.setText(_translate("WizardPage", "show", None))
        self.label_6.setToolTip(_translate("WizardPage", "Text for column title that appears on forest plot", None))
        self.label_6.setText(_translate("WizardPage", "col 2 label:", None))
        self.col2_str_edit.setText(_translate("WizardPage", "[default]", None))
        self.show_2.setText(_translate("WizardPage", "show", None))
        self.label_12.setToolTip(_translate("WizardPage", "Text for column title that appears on forest plot", None))
        self.label_12.setText(_translate("WizardPage", "col 3 label:", None))
        self.col3_str_edit.setText(_translate("WizardPage", "Ev/Trt", None))
        self.show_3.setText(_translate("WizardPage", "show", None))
        self.label_13.setToolTip(_translate("WizardPage", "Text for column title that appears on forest plot", None))
        self.label_13.setText(_translate("WizardPage", "col 4 label:", None))
        self.col4_str_edit.setText(_translate("WizardPage", "Ev/Ctrl", None))
        self.show_4.setText(_translate("WizardPage", "show", None))
        self.x_lbl_le.setText(_translate("WizardPage", "[default]", None))
        self.plot_lb_le.setText(_translate("WizardPage", "[default]", None))
        self.label_10.setText(_translate("WizardPage", "x-axis upper bound", None))
        self.label_8.setText(_translate("WizardPage", "x ticks:", None))
        self.plot_ub_le.setText(_translate("WizardPage", "[default]", None))
        self.x_ticks_le.setText(_translate("WizardPage", "[default]", None))
        self.label_11.setText(_translate("WizardPage", "show summary line:", None))
        self.label_9.setText(_translate("WizardPage", "x-axis lower bound", None))
        self.label_7.setText(_translate("WizardPage", "x label:", None))
        self.label_4.setText(_translate("WizardPage", "save image to:", None))
        self.image_path.setText(_translate("WizardPage", "./r_tmp/forest.png", None))
        self.save_btn.setText(_translate("WizardPage", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.forest_plot_tab), _translate("WizardPage", "forest plot", None))

